site_name: Pak Docs
theme:
  name: material
  palette:
    scheme: slate
    icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
repo_url: https://github.com/Interfiber/pak
repo_name: Interfiber/pak